In [1]:
import numoy as np

ModuleNotFoundError: No module named 'numoy'

In [2]:
import numpy as np


In [3]:
x = [1, 2, 3, 4]
print(x)
print(2*x)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
x = np.array[1, 2, 3, 4]

print(2 * x)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [5]:
x = np.array([1, 2, 3, 4])

print(2 * x)

[2 4 6 8]


In [6]:
print(x + 2)
print(x ** 2)
print(math.sin(x))

[3 4 5 6]
[ 1  4  9 16]


NameError: name 'math' is not defined

In [7]:
import math 


In [8]:
print(x + 2)
print(x ** 2)
print(math.sin(x))

[3 4 5 6]
[ 1  4  9 16]


TypeError: only 0-dimensional arrays can be converted to Python scalars

In [9]:
print(x + 2)
print(x ** 2)

[3 4 5 6]
[ 1  4  9 16]


In [10]:
print(np.sin(x))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
n = np.array([0.1, 0.2, 0.3, 0.4])

def logistic(x,r)
    return r * x * (1 - x)

print(logistic(x))

SyntaxError: expected ':' (421104623.py, line 3)

In [12]:
print(logistic(n,3))

NameError: name 'logistic' is not defined

In [13]:
n = np.array([0.1, 0.2, 0.3, 0.4])
def logistic(x,r)
    return r * x * (1 - x)

print(logistic(n,3))

SyntaxError: expected ':' (707279438.py, line 2)

In [14]:
n = np.array([0.1, 0.2, 0.3, 0.4])
def logistic(x,r):
    return r * x * (1 - x)

print(logistic(n,3))

[0.27 0.48 0.63 0.72]


In [16]:
n = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

for i in range(10):
    n = logistic(n,3.9)
print(n)


[0.96938361 0.09796598 0.18312364 0.12180536 0.10400971]


In [17]:
x = np.linspace(0,1,11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [19]:
x = 0.1
iterate = [x]

for i in range(100): 
    x = logistic(x, 3.9)
    iterate.append(x)

print(iterate)


[0.1, 0.35100000000000003, 0.8884161, 0.3866184397170808, 0.9248640249724619, 0.2710131851083772, 0.7705036505625796, 0.6896283226260395, 0.8347602871063352, 0.5379486456882877, 0.9693836111326567, 0.11574819984026098, 0.3991671608886, 0.9353476803712645, 0.23584234906190144, 0.702860868258376, 0.8145051257048855, 0.5892374510308812, 0.9439430416006932, 0.20636684567586822, 0.6387403256584763, 0.8999293759411018, 0.3512203276115074, 0.888671975427494, 0.3858429725174291, 0.9241758749977399, 0.2732918255726168, 0.7745532742264324, 0.6810199484850271, 0.8472039351768648, 0.5048527668510281, 0.9749081575501692, 0.09540274337998415, 0.33657413374867245, 0.8708387463360124, 0.438666634442145, 0.9603290512504513, 0.14857894184195153, 0.49336263554400234, 0.974828187033005, 0.09569895191590352, 0.33750858382059434, 0.8720265047052437, 0.43522549120751725, 0.9586366257417009, 0.15464453756024107, 0.509845457795779, 0.974621961147087, 0.09646257658788289, 0.3399144368330479, 0.8750531886155272,

In [20]:
print(len(iterate))

101


In [22]:
x = np.linspace(0,1,100)
print(x)
print(x.shape)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
B = np.array([[1,2,3,4],[5,5,6,7],[8,9,9,10]])

print(B.shape)

(3, 4)


In [27]:
trajectory = np.zeros((4,5))

print(trajectory)
print(trajectory.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)


In [28]:
trajectory[0, 2] = 7
print(trajectory)

[[0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
print(trajectory[0])

[0. 0. 7. 0. 0.]


In [35]:
x = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

trajectory = np.zeros((11,5))
trajectory[0] = x

for i in range(1,11): 
    trajectory[i] = logistic(trajectory[i - 1],3.9)

print(trajectory)

[[0.1        0.2        0.3        0.4        0.5       ]
 [0.351      0.624      0.819      0.936      0.975     ]
 [0.8884161  0.9150336  0.5781321  0.2336256  0.0950625 ]
 [0.38661844 0.30321373 0.95119196 0.69827425 0.33549992]
 [0.92486402 0.82397314 0.18106067 0.82168056 0.86946493]
 [0.27101319 0.56566147 0.57828305 0.57143431 0.44263311]
 [0.77050365 0.95818543 0.95109988 0.95509884 0.96216526]
 [0.68962832 0.15625784 0.1813847  0.16725167 0.14197278]
 [0.83476029 0.51418118 0.57908873 0.54318635 0.47508439]
 [0.53794865 0.97421569 0.95060539 0.96772626 0.97257893]
 [0.96938361 0.09796598 0.18312364 0.12180536 0.10400971]]


In [38]:
print(trajectory[:, 2])

[0.3        0.819      0.5781321  0.95119196 0.18106067 0.57828305
 0.95109988 0.1813847  0.57908873 0.95060539 0.18312364]


In [39]:
print(trajectory[2:6, 3:5])

[[0.2336256  0.0950625 ]
 [0.69827425 0.33549992]
 [0.82168056 0.86946493]
 [0.57143431 0.44263311]]
