In [ ]:
#Scores is an np.array, getting numbers, and these numbers can be any real number with no condition. Then using Gibbs measure, we can convert them to be probability distribution. We simply take each element of the array and exp of that element, devided by the normalizer(meaning sum of all exps) will give us a Gibbs probability measure.



import numpy as np
import matplotlib.pyplot as plt
#softmax is the last part of the algorithm in "Attention is all you need" paper. We here feed scores array to this softmax,but how that scores array produced in first place? That's what Attention does./ tau is the temprature in Gibbs definition. 
def softmax(scores, tau) : 
    scores = np.asarray(scores,dtype = float)
    z = np.max(scores)
    scores = scores - z
    exp_scores = np.exp(scores/tau)
    normalizer = np.sum(exp_scores)
    probabilities  = exp_scores/normalizer #Gibbs measure 
    L = -np.log(probabilities[1]) #Loss Function

    return probabilities, L

In [14]:
for tau in [0.1,1,10,100]:
    print(softmax(np.array([2,1,-1]), tau))

(array([9.99954602e-01, 4.53978687e-05, 9.35719815e-14]), np.float64(10.00004539889931))
(array([0.70538451, 0.25949646, 0.03511903]), np.float64(1.3490122167681864))
(array([0.37797814, 0.34200877, 0.28001309]), np.float64(1.0729189131256587))
(array([0.33778131, 0.33442033, 0.32779836]), np.float64(1.0953566081506636))


In [ ]:
#Here we will use the formulas in Attention paper, to calculate scores, then probability distribution, and then output using these formulas: s_j = \frac{q^T k_j}{sqrt{d_k}}, d_k is the number of components, so for our example here it's just 2. q is a vector, k is a vector, q^T gives another vector and q^T k_j matrix will give a scalar. 
#Then we will use th eformula alpha_j = e^{s_j}/sum e^{s_i}, so these alpha_j are Gibbs distribution, and finally output vector is o = sum alpha_jv_j. 

q = np.array([1,0])
k1 = np.array([2,0])
k2 = np.array([1,1])
k3 = np.array([-1,2])
v1 = np.array([10,0])
v2 = np.array([0,10])
v3 = np.array([4,4])

scores = []
d = len(q)

s1 = q.T @ k1 / np.sqrt(d)
s2 = q.T @ k2 / np.sqrt(d)
s3 = q.T @ k3 / np.sqrt(d)
scores.append(s1)
scores.append(s2)
scores.append(s3)

print(scores)


#Here we need to pass these scores through our softmax function, to get values for alpha_j.

alpha = softmax(scores,1)[0] 
print(alpha)

#Then here we calculate the output vector. 

output_vector = alpha[0] * v1 + alpha[1] * v2 + alpha[2] * v3
print(output_vector)


    



[np.float64(1.414213562373095), np.float64(0.7071067811865475), np.float64(-0.7071067811865475)]
[0.61998512 0.30569525 0.07431963]
[62.29579033  3.35423103]


In [31]:
# Here we will run the same experiment but this time, those vectors all stacked together to obtain a matrix. 
K = np.stack([k1,k2,k3])
V = np.stack([v1,v2,v3])

output = softmax((q @ K.T) / np.sqrt(d),1)[0] @ V
print(output)


[62.29579033  3.35423103]
